logging:
  level:
    root: warn
    org:
      springframework:
        security: warn
      apereo:
        cas: info
casbot:
  github:
    repository:
      organization: apereo
      name: cas
      url: https://github.com/apereo/cas
      admins: mmoayyed,apereocas-bot
      committers: leleuj,mmoayyed,apereocas-bot
    staging-repository:
      organization: mmoayyed
      name: cas
      url: https://github.com/mmoayyed/cas
      admins: mmoayyed,apereocas-bot
      committers: mmoayyed,apereocas-bot
      
spring:
  security:
    user:
      name: apereocasbot
      password: ${casbot.github.repository.credentials.token}
      roles: ADMIN
  jackson:
    default-property-inclusion: non_null
